# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: nosetests

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
    - name: Install other compilers
      run: |
        sudo apt-get update
        sudo apt-get install nim mono-complete
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autopep8
        pip install codecov nose
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install .
    - name: Lint with flake8
      run: |
        flake8 --ignore=E501,W503,W605 --exclude=atcodertools/tools/templates/,tests/resources/test_codegen/ atcodertools tests
        autopep8 -r . --exclude 'default_template.py,test_codegen' --diff | tee check_autopep8
        test ! -s check_autopep8
    - name: Test with nosetests
      run: |
        atcoder-tools gen arc050 --without-login
        nosetests tests --exe -v --with-coverage --cover-package=atcodertools
        codecov
